package com.autumnharvestc.server.store;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 显式 id 插入通道（规格 2026-09-09 BIGINT 化口径 8）：外部策略 appAssigned()=true 时，
 * users/workspaces/groups/projects 四仓储走 INSERT_WITH_ID_SQL 分支——nextId() 预生成 id
 * 显式落库且 find 往返一致。同时钉死 GENERATED BY DEFAULT AS IDENTITY 的另一半契约：
 * 显式 id 插入不耗尽/不干扰 identity 自增序列——假策略切回 identity 模式再插入，
 * 主键仍由库自增（值与显式 id 天然错开、无主键冲突）。
 * 假策略自计数从 1000 起（identity 序列自 1 起），两形态取值空间分离，互扰即测试失败。
 */
@JdbcTest
@Import({UserRepo.class, WorkspaceRepo.class, GroupRepo.class, ProjectRepo.class,
        AppAssignedInsertTest.CountingFromThousandIds.class})
@Transactional
class AppAssignedInsertTest {

    private static final Instant NOW = Instant.now().truncatedTo(ChronoUnit.MICROS);

    @Autowired
    private UserRepo users;

    @Autowired
    private WorkspaceRepo workspaces;

    @Autowired
    private GroupRepo groups;

    @Autowired
    private ProjectRepo projects;

    @Autowired
    private CountingFromThousandIds ids;

    @BeforeEach
    void resetFakeStrategy() {
        ids.reset();
    }

    /** users：显式 id=1000 落库 + findById 往返全字段一致；切回 identity 后继续库自增且不与显式 id 撞键。 */
    @Test
    void userExplicitIdInsertRoundTripsAndIdentitySequenceUnaffected() {
        UserAccount saved = users.insert(new UserAccount(null, "alice", "$2a$10$hash",
                "显示名-alice", PlatformRole.USER, false, NOW));
        assertThat(saved.id()).as("应回填假策略预生成的 id").isEqualTo(1000L);

        UserAccount out = users.findById(1000L).orElseThrow();
        assertThat(out.username()).isEqualTo("alice");
        assertThat(out.passwordHash()).isEqualTo("$2a$10$hash");
        assertThat(out.displayName()).isEqualTo("显示名-alice");
        assertThat(out.role()).isEqualTo(PlatformRole.USER);
        assertThat(out.disabled()).isFalse();
        assertThat(out.createdAt()).isEqualTo(NOW);

        ids.useIdentity();
        long first = users.insert(new UserAccount(null, "bob", "$2a$10$hash",
                "显示名-bob", PlatformRole.USER, false, NOW)).id();
        long second = users.insert(new UserAccount(null, "carol", "$2a$10$hash",
                "显示名-carol", PlatformRole.USER, false, NOW)).id();
        assertThat(first).as("显式 id 未耗尽 identity 序列").isLessThan(1000L);
        assertThat(second).isGreaterThan(first);
    }

    /** workspaces：显式 id 落库 + findById 往返一致；identity 序列不受显式 id 干扰。 */
    @Test
    void workspaceExplicitIdInsertRoundTripsAndIdentitySequenceUnaffected() {
        WorkspaceRecord saved = workspaces.insert(new WorkspaceRecord(null, "显式工作区", 1000L, NOW));
        assertThat(saved.id()).isEqualTo(1000L);

        WorkspaceRecord out = workspaces.findById(1000L).orElseThrow();
        assertThat(out.name()).isEqualTo("显式工作区");
        assertThat(out.createdBy()).isEqualTo(1000L);
        assertThat(out.createdAt()).isEqualTo(NOW);

        ids.useIdentity();
        long first = workspaces.insert(new WorkspaceRecord(null, "自增工作区甲", 1000L, NOW)).id();
        long second = workspaces.insert(new WorkspaceRecord(null, "自增工作区乙", 1000L, NOW)).id();
        assertThat(first).isLessThan(1000L);
        assertThat(second).isGreaterThan(first);
    }

    /** groups：显式 id 落库 + find 往返一致；identity 序列不受显式 id 干扰。 */
    @Test
    void groupExplicitIdInsertRoundTripsAndIdentitySequenceUnaffected() {
        GroupRecord saved = groups.insert(new GroupRecord(null, 1L, "显式分组", false, NOW));
        assertThat(saved.id()).isEqualTo(1000L);

        GroupRecord out = groups.find(1000L).orElseThrow();
        assertThat(out.workspaceId()).isEqualTo(1L);
        assertThat(out.name()).isEqualTo("显式分组");
        assertThat(out.isDefault()).isFalse();
        assertThat(out.createdAt()).isEqualTo(NOW);

        ids.useIdentity();
        long first = groups.insert(new GroupRecord(null, 1L, "自增分组甲", false, NOW)).id();
        long second = groups.insert(new GroupRecord(null, 1L, "自增分组乙", false, NOW)).id();
        assertThat(first).isLessThan(1000L);
        assertThat(second).isGreaterThan(first);
    }

    /** projects：显式 id 落库（先以显式通道备好外键 groups 行）+ find 往返一致；identity 序列不受显式 id 干扰。 */
    @Test
    void projectExplicitIdInsertRoundTripsAndIdentitySequenceUnaffected() {
        long groupId = groups.insert(new GroupRecord(null, 1L, "挂载分组", false, NOW)).id();
        assertThat(groupId).isEqualTo(1000L);

        ProjectRecord saved = projects.insert(new ProjectRecord(null, 1L, groupId, "显式项目", NOW));
        assertThat(saved.id()).isEqualTo(1001L);

        ProjectRecord out = projects.find(1001L).orElseThrow();
        assertThat(out.workspaceId()).isEqualTo(1L);
        assertThat(out.groupId()).isEqualTo(groupId);
        assertThat(out.name()).isEqualTo("显式项目");
        assertThat(out.createdAt()).isEqualTo(NOW);

        ids.useIdentity();
        long first = projects.insert(new ProjectRecord(null, 1L, groupId, "自增项目甲", NOW)).id();
        long second = projects.insert(new ProjectRecord(null, 1L, groupId, "自增项目乙", NOW)).id();
        assertThat(first).isLessThan(1000L);
        assertThat(second).isGreaterThan(first);
    }

    /**
     * 假外部策略：appAssigned=true，nextId 自计数（1000 起）；可切回 identity 模式，
     * 复用同一仓储 Bean 的另一条插入分支（spec 口径 8 的往返验证通道）。
     */
    static class CountingFromThousandIds implements IdGeneration {

        private boolean appAssigned = true;
        private long next = 1000L;

        void reset() {
            this.appAssigned = true;
            this.next = 1000L;
        }

        void useIdentity() {
            this.appAssigned = false;
        }

        @Override
        public boolean appAssigned() {
            return appAssigned;
        }

        @Override
        public long nextId() {
            return next++;
        }
    }
}
