package com.autumnharvestc.server.store;

/**
 * 实体 id 生成策略（规格 2026-09-09 BIGINT 化口径 2）：可插拔——默认 identity=数据库自增
 * （插入不带 id、KeyHolder 取回）；外部策略（如雪花）实现 appAssigned()=true，仓储插入前
 * 经 nextId() 预生成显式插入（DDL 用 GENERATED BY DEFAULT AS IDENTITY，两种形态共存）。
 * 本轮只交付 identity；snowflake 等按需另配实现类。
 */
public interface IdGeneration {

    /** true = 应用侧预生成（insert 前 nextId()）；false = 数据库 IDENTITY 自增。 */
    boolean appAssigned();

    /** 应用侧生成下一个 id（仅 appAssigned()=true 时被仓储调用）。 */
    long nextId();
}
